### ISSUE TITLE
incorrect process num

### ISSUE THREAD

**Issue by andre-merzky** [markovmodel/PySFD#5]
Hi Sebastian, 

I think the process counts in your code don't do what you expect them to do.  Have a look at this diff: https://github.com/andre-merzky/PySFD/pull/1/commits/4ea9a1fa51e3d0a8036c0bb6924fefc536238104

Run the example on a 4 core machine with `maxprocs=[5,5]`.  You would
expect 5 prints for `run_ens` and 5 prints for `ffunc`.  You will
observe 3 prints and 9 prints.

The reason is this: the first process pool will detect 4 cores, and
realizes one is used by the current process, so it will create at most
3 additional processes (even when 5 are requested).  This results in
3 `run_ens` prints.

On the next level, each of those aggregator processes will create its
*own* (private) process pool, each of which will do the same spiel and
spawn at most 3 additional processes (even though 5 are requested): each
aggregator process pool will not see the other process pools, and thus thinks
3 cores are unused.  We thus end up with 3*3=9 `ffunc` prints.

Or *is* this the intended behavior?

**Comment by sstolzenberg** [comment]
Hello Andre,

Thanks for testing my code.

In the "PySFD_example" you tested, I had placed 3 MD "ensembles" each with 3 MD trajectories into the "input" folder, which is why you received 3 "run_ens" and 9 "ffunc" prints.

Your observation is still very useful, since I just noticed that the pathos (multiprocessing) module does not throw any warning if maxworkers is e.g. (10, 10) on a 4-core machine!
I have now added this warning message in:
markovmodel@a3f9486

Thanks,
Sebastian
